const tickets = [
  {
    category: "Q1 222",
    color: "red",
    title: "NFT Safety 101 Video",
    owner: "hedi",
    avatar: "https://i.postimg.cc/hGHnhhB4/hedii.jpg",
    status: "done",
    priority: 5,
    progress: 40,
    description: "Make a video showcasing how to work on nfts safely",
    timestamp: "2022-09-29",
  },
  {
    category: "Q1 222",
    color: "blue",
    title: "Web 3.0",
    owner: "hedi",
    avatar: "https://i.postimg.cc/hGHnhhB4/hedii.jpg",
    status: "working on it",
    priority: 5,
    progress: 40,
    description: "Make a video showcasing how to work on nfts safely",
    timestamp: "2022-09-29",
  },
  {
    category: "Q1 200",
    color: "red",
    title: "Blockchain",
    owner: "hedi",
    avatar: "https://i.postimg.cc/hGHnhhB4/hedii.jpg",
    status: "done",
    priority: 5,
    progress: 40,
    description: "Make a video showcasing how to work on nfts safely",
    timestamp: "2022-09-29",
  },
];
